### PR TITLE
Added setup instructions

### PR DESCRIPTION
**Pull request by minihoot**
I added setup instructions that I borrowed from Cedar-Django's readme.

### CODE REVIEW

**Comment by ariankordi** [comment]
lmao you didn't even finish renaming Cedar-Django in the systemd config.........
so to be REDDIT about it, I'm not a FAN of these instructions, runserver under root isn't the way God ever intended to run Closedverse, gunicorn is preferred. the project also has a requirements.txt so the pip install line is kind of unnecessary, you SHOULD be able to run pip install -r requirements.txt. (actually... passlib, lxml, django-markdown2, django-xff, aren't STRICTLY necessary anymore. guess I'll have to update that too?)
BUT it is better than nothing, fine. As a consolation prize, I will fix your Indigo issue and think about this later.

**Comment by minihoot** [comment]
shit i forgot to remove  that from systemd sorry

**Comment by ariankordi** [comment]
I just wrote my own tutorial. I wanted it to do it my way, but I did reference the Cedar-Django one in the README. I'm not 100% fully sure that everything functions, but let's just say, about 70%. If you find any issues with it, let me know.

**Comment by minihoot** [comment]
I'll say mine is for a development environment.

**Comment by minihoot** [comment]
I'm testing the instructions you wrote now, if I have issues I'll message you on Discord.

**Pull request closed without merging**
